version: "3.9"
services:

  core-api:
    build:
      context: ./noweekend-core/core-api
    image: core-api:latest
    ports:
      - "8080:8080"
    environment:
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
      SPRING_PROFILES_ACTIVE: local
      SERVER_PORT: 8080
    networks:
      - mashupnet

networks:
  mashupnet:
    external: true
