version: "3.9"
services:
  core-api:
    image: core-api:latest
    ports:
      - "8080:8080"
    environment:
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
      SPRING_PROFILES_ACTIVE: staging
      SERVER_PORT: 8080
    networks:
      - mashupnet

  mcp-server:
    image: mcp-server:latest
    ports:
      - "8081:8081"
    environment:
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
      SERVER_PORT: 8081
    networks:
      - mashupnet

  mcp-host:
    image: mcp-host:latest
    environment:
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
      SERVER_PORT: 8082
    depends_on:
      - mcp-server
    networks:
      - mashupnet

networks:
  mashupnet:
    external: true
