version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mash-up-noweekend
      MYSQL_USER: mash-up-noweekend
      MYSQL_PASSWORD: mash-up-noweekend
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mashupnet

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - mashupnet
volumes:
  mysql-data:

networks:
  mashupnet:
    external: true