spring.application.name: core-api
spring.profiles.active: local

spring:
  config:
    import:
      - monitoring.yml
      - logging.yml
      - db-core.yml
      - client-apple.yml
      - client-kakao.yml
      - client-mcp.yml
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

jwt:
  secret: ENC(NlQZbTD2BJvq1B2SjY2NZazSBwND6KsuQGRGN65eUeODAdDv29aU3iOxo8PNylhFqv1adtCvyxfuNYPTBQGQDtJ09iNxJdF3WhPrdgSHi/U=)
  issuer: https://www.noweekend.com
  expiration: 86400000

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live

