spring:
  ai:
    anthropic:
      api-key: ENC(DSDMqqudORinUFWutrGj/hFq31Rcp+1B5SqZmhQUZKe5g5G01KIcngKwmep3K0aDGrqMIGsxlAxj9Bx9fe2MwHnpQ+pZYCT/vYAp/6hKIiuSQULyrMWgkTxd08+RWnzP9DNZb7BpX1NYuZ3dsIqPo0qVCVsyLLjc)
      chat:
        options:
          model: claude-3-7-sonnet-20250219

    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: true
        sse:
          connections:
            author-tool-server:
              url: http://localhost:8081
              enabled: true
        stdio:
          connections:
            brave-search:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: ENC(tOf1NF3MQ4QX7ou+iVM6BoOB5NrW2B9KkZVC3jn72puMsagRysNFGA==)
        type: SYNC
        request-timeout: 60s

logging:
  level:
    org:
      springframework:
        ai: DEBUG

server:
  port: 8082

JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_VALUE}