spring:
  jackson:
    time-zone: Asia/Seoul
  mvc:
    time-zone: Asia/Seoul
  ai:
    anthropic:
#      api-key: ENC(DSDMqqudORinUFWutrGj/hFq31Rcp+1B5SqZmhQUZKe5g5G01KIcngKwmep3K0aDGrqMIGsxlAxj9Bx9fe2MwHnpQ+pZYCT/vYAp/6hKIiuSQULyrMWgkTxd08+RWnzP9DNZb7BpX1NYuZ3dsIqPo0qVCVsyLLjc)
      api-key: ENC(q6WkPzavRozxQbgOktG6eCgCIMtfAlLQuakXP4sBXPDS+Ij8dvo9p0GJyE0+FJgEOkhys5DM50qsMOedjdZS5ewcc1ACvpRw6TcHWi7Mu158YCQUC5M4A5RGqC5ACDNnbrjrA1dmmJtEi8dNHCPlYLXRKK2m/t5Z)
      chat:
        options:
          model: claude-3-7-sonnet-20250219

    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: true
        sse:
          connections:
            author-tool-server:
              # prod
              url: http://mcp-server:8081
              # local
#              url: http://localhost:8081
              enabled: true
#        stdio:
#          connections:
#            brave-search:
#              command: npx
#              args:
#                - "-y"
#                - "@modelcontextprotocol/server-brave-search"
#              env:
#                BRAVE_API_KEY: ENC(tOf1NF3MQ4QX7ou+iVM6BoOB5NrW2B9KkZVC3jn72puMsagRysNFGA==)
        type: SYNC
        request-timeout: 60s

logging:
  level:
    org:
      springframework:
        ai: DEBUG

server:
  port: 8082

JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_VALUE}
