spring:
  ai:
    mcp:
      server:
        name: author-tool-server
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/message
        stdio: false
        enabled: true

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        ai: DEBUG

JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_VALUE}

kma:
  api:
    key: ENC(Tc+YYC2ra7u6yRSzxf7g8T+5X60RlwiW+F79TEDF39JI1xB2wSnx/GBVQx0egxehLS/erq3jO6ZPd0jAYyvRD77cRtMECJeyVdOpgfB3TJtIF3f39LTeaYqAn0xWgAit+WcGS/dgmqQ=)


#resilience4j:
#  ratelimiter:
#    instances:
#      amadeus:
#        limit-for-period: 8
#        limit-refresh-period: 1s
#        timeout-duration: 30s
#        subscribe-for-events: true
#        register-health-indicator: true
#  retry:
#    instances:
#      amadeus:
#        max-attempts: 3
#        wait-duration: 1s
#        retry-exceptions:
#          - feign.FeignException.TooManyRequests
