name: Deploy to NCP

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Build core-api jar
        run: ./gradlew :noweekend-core:core-api:clean :noweekend-core:core-api:bootJar

      - name: Build mcp-host jar
        run: ./gradlew :noweekend-mcp:mcp-host:clean :noweekend-mcp:mcp-host:bootJar

      - name: Build mcp-server jar
        run: ./gradlew :noweekend-mcp:mcp-server:clean :noweekend-mcp:mcp-server:bootJar

      - name: Build core-api Docker image
        run: docker build -t core-api:latest -f ./noweekend-core/core-api/Dockerfile ./noweekend-core/core-api

      - name: Save Docker images as tar
        run: |
          docker save core-api:latest -o core-api.tar

      - name: SCP Docker images and Compose file to NCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.NCP_SERVER_HOST }}
          username: root
          key: ${{ secrets.NCP_SSH_KEY }}
          source: |
            core-api.tar
            docker-compose.app.yml
          target: /root/organized/app/

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.NCP_SERVER_HOST }}
          username: root
          key: ${{ secrets.NCP_SSH_KEY }}
          script: |
            cd /root/organized/app
            docker load -i core-api.tar
            docker compose -f docker-compose.app.yml up --build -d
